Ag:
  Utility:
    CommandQueue:
      Log: FALSE

    #StatsdWriter:
      #enabled: TRUE
      #keyPrefix: demo
      #host: 127.0.0.1
      #port: 8125


TYPO3:
  Flow:
    object:
      excludeClasses:
        'mlehner.gelfphp' : ['.*']
        'pda.pheanstalk' : ['.*']

#    log:
#      systemLogger:
#        backend:
#          - TYPO3\Flow\Log\Backend\FileBackend
#          - Ag\Utility\Log\Backend\EmailBackend
#          - Ag\Utility\Log\Backend\GelfBackend
#        backendOptions:
#          0:
#            logFileURL: %FLOW_PATH_DATA%Logs/System.log
#            createParentDirectories: TRUE
#            severityThreshold: %LOG_INFO%
#            maximumLogFileSize: 10485760
#            logFilesToKeep: 1
#            logMessageOrigin: FALSE
#          1:
#            severityThreshold: %LOG_CRIT%
#            from: 'no-reply@agitso.com'
#            subject: 'Log message'
#            emails:
#              - 'hmr@agitso.com'
#          2:
#            severityThreshold: %LOG_INFO%
#            host: '127.0.0.1'
#            facility: '<SiteName>'